### ISSUE TITLE
A new URL

### ISSUE THREAD

**Issue by gasparfm** [linuxitux/blogosfera#2]
Hola, 

Me haría mucha ilusión salir en el ranking linuxero :) Mi URL es https://totaki.com/poesiabinaria . No sé si habría mucho problema al no ser el dominio directamente. De todas formas, prácticamente lo único que hay en ese dominio es mi blog.

Un saludo !!!

**Comment by linuxitux** [comment]
Alexa sólo rankea dominios :/

https://www.alexa.com/siteinfo

**Comment by gasparfm** [comment]
Mira que llevo tiempo queriendo meterlo en un dominio para el solo... en fin, como me de el punto un dia de estos...

Gracias

**Comment by linuxitux** [comment]
Es malo para el SEO, hacelo cuanto antes.

**Comment by gasparfm** [comment]
¿Te refieres a comprar el dominio ahora? O a no tenerlo. Yo al principio me quedé con mi dominio más que nada por la antiguedad.

**Comment by gasparfm** [comment]
Al final me armé de valor y pillé poesiabinaria.net . A ver cómo me va con el SEO, los agregadores y demás y casi casi tendré para un post.
Todavía, normal, Alexa no sabe de mi existencia.

**Comment by linuxitux** [comment]
Bien, te va a mejorar el SEO. Cierro.
