### ISSUE TITLE
Falta la licencia

### ISSUE THREAD

**Issue by jorgesumle** [linuxitux/blogosfera#3]
No sé si este proyecto está pensado para ser software libre. Si quieres que sea libre, puedes ponerle [cualquier licencia libre](https://www.gnu.org/licenses/license-list.es.html). Si no, también estaría bien aclarar que no es un proyecto libre en alguna parte.

**Comment by linuxitux** [comment]
Todo el software que aquí publico es libre. Supongo que debería agregar alguna licencia.

**Comment by jorgesumle** [comment]
> Todo el software que aquí publico es libre.

Sin licencia no es libre, esa es la razón por la que desarrollo el copyleft y las licencias libres y de dominio público.
